#!/usr/bin/env bash

NODE_ROOT="$(readlink -f $(dirname "${BASH_SOURCE[0]}")/../..)"
RESULT_FILE="${NODE_ROOT}/scripts/debug"
cat <<EOF > "${RESULT_FILE}"
{"status": "processing"}
EOF

encode_for_json () {
  jq --null-input --raw-input 'reduce inputs as $line (""; . += "\($line)\n")'
}

debug_json_string=$("${NODE_ROOT}/scripts/debug" --no-colors --no-instructions --filter | encode_for_json)
dmesg_json_string=$(dmesg | encode_for_json)

cat <<EOF > "${RESULT_FILE}"
{
  "status": "success",
  "debug": ${debug_json_string},
  "dmesg": ${dmesg_json_string}
}
EOF

