#!/usr/bin/env bash

set -euo pipefail

NODE_ROOT="$(readlink -f $(dirname "${BASH_SOURCE[0]}")/../..)"
PASSWORD_FILE="${NODE_ROOT}/statuses/password"

check_root () {
  if [[ $UID != 0 ]]; then
    echo "This script must be run as root"
    exit 1
  fi
}

get_username () {
  [[ -f "/etc/default/umbrel" ]] && source "/etc/default/umbrel"
  [[ -f "/etc/default/citadel" ]] && source "/etc/default/citadel"
  # Throw an error if neither CITADEL_OS nor UMBREL_OS are set
  [[ -z "${CITADEL_OS:-}" && -z "${UMBREL_OS:-}" ]] && {
    echo "CITADEL_OS or UMBREL_OS must be set"
    exit 1
  }
  # If UMBREL_OS is set, return umbrel, otherwise return citadel
    [[ -n "${UMBREL_OS:-}" ]] && echo "umbrel" || echo "citadel"
}

password="$(cat ${PASSWORD_FILE})"
echo "false" > "${PASSWORD_FILE}"

check_root
USERNAME=$(get_username)

if [[ "${password}" == "" ]] || [[ "${password}" == "false" ]] || [[ "${password}" == "true" ]]; then
  echo "Password not set in status file: \"${PASSWORD_FILE}\""
  exit 1
fi

echo -e "${password}\n${password}" | passwd ${USERNAME}
echo "true" > "${PASSWORD_FILE}"
